# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Hyundong Jin 
title: Curriculum Vitae
email: jude0316@cau.ac.kr
website: https://vllab.cau.ac.kr/members/


# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  Jin0316
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: About Me
about_profile_image: images/profile_hyundongjin.png

about_content: | # this will include new lines to allow paragraphs
  Hyundong Jin received the B.S degree in Electrical and Electronics Engineering from Chung-Ang Univrsity, in 2020, 
  and the M.S degree in School of Computer Science and Engineering from Chung-Ang University in 2022. 
  
  He is currently Ph.D candidate in School of Computer Science of Chung-Ang University. 
 
  His research interests include deep learning, machine learning, continual learning, and computer vision.

  He is most skilled in: Continual Learning. [ [**CV**] ](https://github.com/Jin0316/HyundongJin.io/blob/main/images/CV.pdf)
content:

  - title: Education  # Title for the section
    layout: list # Type of content section (list/text)
    content:     
      - layout: left
        title: Chung-Ang University
        caption: Mar. 2022 - present
        description: | # this will include new lines to allow paragraphs
            **Ph.D. Candidate** - School of Computer Science and Engineering (advisor: [**Eunwoo Kim**](https://vllab.cau.ac.kr/members/professor/))
            
      - layout: left
        title: Chung-Ang University
        caption: Mar. 2020 - Feb.2022
        description: | # this will include new lines to allow paragraphs
            **Master degree** - School of Computer Science and Engineering (advisor: [**Eunwoo Kim**](https://vllab.cau.ac.kr/members/professor/))
            
      - layout: left
        title: Chung-Ang University
        caption: Mar. 2015 - Feb.2020
        description: | # this will include new lines to allow paragraphs
            **Bachelor degree** - Electrical and Electronics Engineering.

##### Paper #####

  - title: International Conference  # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: ICCV 2023
        link: https://scholar.google.com/citations?view_op=top_venues&hl=en&vq=eng_computervisionpatternrecognition
        link_text: Google Scholar
        sub_title: Top-tier Conference in Computer Vision & Machine Learning
        caption: 
        quote: >
        description: | # this will include new lines to allow paragraphs
           #### Growing a Brain with Sparsity-Inducing Generation for Continual Learning, 
           
           **Hyundong Jin**, Gyeong-Hyeon Kim, Chanho Ahn, and Eunwoo Kim. [ [Paper] ](https://openaccess.thecvf.com/content/ICCV2023/papers/Jin_Growing_a_Brain_with_Sparsity-Inducing_Generation_for_Continual_Learning_ICCV_2023_paper.pdf) [ [Code] ](https://github.com/Jin0316/GrowBrain)
           
      - layout: left
        title: ECCV 2022
        link: https://scholar.google.com/citations?view_op=top_venues&hl=en&vq=eng_computervisionpatternrecognition
        link_text: Google Scholar
        sub_title: Top-tier Conference in Computer Vision & Machine Learning
        caption: 
        quote: >
        description: | # this will include new lines to allow paragraphs
           #### Helpful or Harmful: Inter-Task Association in Continual Learning, 
           
           **Hyundong Jin** and Eunwoo Kim [ [Paper] ](https://www.ecva.net/papers/eccv_2022/papers_ECCV/papers/136710518.pdf) [ [Code] ](https://github.com/Jin0316/Helpful-or-Harmful-Inter-Task-Association)
 
  - title: International Journal  # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: IEEE Access 2023
        sub_title: International Journal
        caption: 
        quote: >
        description: |
           #### Task-Aware Dynamic Model Optimization for Multi-Task Learning, (Accepted)

           Sujin Choi*, Hyundong Jin*, and Eunwoo Kim (* denotes for equal contribution)
           
           
      - layout: left
        title: IEEE Access 2022
        sub_title: International Journal
        caption: Impact Factor 3.367 (2022)
        quote: >
        description: |
           #### Gating Mechanism in Deep Neural Networks for Resource-Efficient Continual Learning, 
           
           **Hyundong Jin**, Kimin Yun, and Eunwoo Kim (**bold font** for first author) [ [Paper] ](https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=9695483)
                       
  - title: Invited Talks  # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Feb. 2023.
        link: 
        # link_text: boringcompany.com
        sub_title: 
        caption: 
        quote: >
        description: | # this will include new lines to allow paragraphs
            #### Korean Computer Vision Society (**KCVS**), 
            
            Continual Learning session.
      - layout: left
        title: Dec. 2022.
        link: 
        # link_text: boringcompany.com
        sub_title: 
        caption: 
        quote: >
        description: | # this will include new lines to allow paragraphs
            #### Korean Artificial Intelligence Association (**KAIA**) and **NAVER**, 
            
            CV / NLP session. 
            
  - title: Project Experiences # Title for the section
    layout: list # Type of content section (list/text)
    content:

      - layout: left
        title: 2021 - present.
        link: 
        link_text: 
        sub_title:
        caption: 
        quote: >
        description: | # this will include new lines to allow paragraphs
            Learning Transferable Task Knowledge and Planner for Service Robots
            
            _Funded by Samsung Research Funding & Incubation Center_      
    
      - layout: left
        title: 2020 - present.
        link: 
        link_text: 
        sub_title:
        caption: 
        quote: >
        description: | # this will include new lines to allow paragraphs
            Development of AI for Self-Improving Competency-Aware Learning
            
            _Funded by IITP_

            
      - layout: left
        title: 2020 - 2022.
        link: 
        link_text: 
        sub_title:
        caption: 
        quote: >
        description: | # this will include new lines to allow paragraphs
            Automated Deep Learning Technology for Multi-Task Learning 
            
            _Funded by National Research Foundation_
            
  - title: Teaching Experiments # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 2021. 
        link: 
        link_text: 
        sub_title:
        caption: 
        quote: >
        description: | # this will include new lines to allow paragraphs
            Capstone Design (Teaching Assistant) in Chung-Ang University (CAU)
            
      - layout: left
        title: 2020.
        link: 
        link_text: 
        sub_title:
        caption: 
        quote: >
        description: | # this will include new lines to allow paragraphs
            Visual Intelligence and it's Applications in Electronics and Telecommunications Research Institute (ETRI)
            
      - layout: left
        title: 2020. 
        link: 
        link_text: 
        sub_title:
        caption: 
        quote: >
        description: | # this will include new lines to allow paragraphs
            Algorithms (Teaching Assistant) in Chung-Ang University (CAU)
           
# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
